export interface UserProgress {
  isEligible: boolean | null;
  hasRegistered: boolean;
  hasRequiredDocs: boolean;
  knowsPollingBooth: boolean;
  badges: string[];
  storedDocs: Record<string, string>; // Category -> Filename/URL
  voterType: 'first-time' | 'returning' | null;
  userName?: string;
  constituency?: string;
  age?: number;
  isCitizen?: boolean;
}

export interface ElectionDate {
  id: string;
  title: string;
  date: string;
  description: string;
  type: 'deadline' | 'event' | 'reminder';
}

export interface Document {
  id: string;
  name: string;
  category: string;
  isMandatory: boolean;
  description: string;
}

export type Language = 'en' | 'hi' | 'bn' | 'ta' | 'mr';

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  isAutoGenerated?: boolean;
}
